# Generated by Django 4.1.2 on 2022-12-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='_class',
            new_name='dept',
        ),
    ]
